CREATE DATABASE EVENTOS_FP_FEE;
USE EVENTOS_FP_FEE;

CREATE TABLE TIPOS
(ID_TIPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
DESCRIPCION VARCHAR(200)
);

CREATE TABLE PERFILES
(ID_PERFIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL
);

insert into perfiles values(1,'ADMON'), (2,'CLIENTE');

CREATE TABLE USUARIOS
(ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(45) NOT NULL UNIQUE,
PASSWORD VARCHAR(250) NOT NULL,
NOMBRE VARCHAR(50),
APELLIDOS VARCHAR(100),
ENABLED INT NOT NULL DEFAULT 1,
FECHA_REGISTRO DATE,
ID_PERFIL INT NOT NULL,
foreign key(ID_PERFIL) REFERENCES PERFILES(ID_PERFIL)
);

insert into usuarios values
(1, 'ramon@fp.com', '12345', 'Ramon', 'Santaolaya Lopez',1,  '2024-03-15', 1),
(2, 'eva@fp.com', '12345', 'Eva', 'Goma Papel',1,  '2025-01-15', 2);



CREATE TABLE EVENTOS
(ID_EVENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nombre varchar(50) not null,
DESCRIPCION VARCHAR(200),
FECHA_INICIO DATE,
UNIDAD_DURACION ENUM('HORAS', 'DIAS'),
DURACION INT,
DIRECCION VARCHAR(100),
AFORO_MAXIMO INT,
ESTADO ENUM('ACTIVO', 'TERMINADO' ,'CANCELADO') default 'ACTIVO',
DESTACADO ENUM('S', 'N'),
PRECIO DOUBLE,
ID_TIPO INT NOT NULL,
FECHA_ALTA DATE,
FOREIGN KEY(ID_TIPO) REFERENCES TIPOS(ID_TIPO)
);

CREATE TABLE RESERVAS
(ID_RESERVA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO INT NOT NULL,
ID_EVENTO INT NOT NULL,
PRECIO_VENTA DOUBLE,
OBSERVACIONES VARCHAR(200),
CANTIDAD INT not null default 1,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
unique(id_usuario,id_evento),
CHECK(CANTIDAD BETWEEN 1 AND 10)
);

